### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by gchoquet** [dotMorten/Windows.Devices.Sensors#2]
When running on my Dell 7202 (which has sensors that I can read using the Microsoft universal windows examples), the application shows no data and closes when I move my 7202 (presumably when a change in the accelerometer is triggered). Attempts to debug using VS2019, return null for .GetDefaut() call. I suspect that an unhandled error is triggering the application to close. 

I'm looking at this application (vs. the universal windows example) because I'm trying to use the data in another application. I can't seem to bridge the gap from UWP to a desktop application without building a custom socket or like method.

**Comment by dotMorten** [comment]
Don't use this old project. Use the C# bindings for the WinRT geolocation APIs now available.

**Comment by gchoquet** [comment]
As I stated, the WinRT implementation is in the universal windows platform. I need access to the sensors in an existing windows forms application.

**Comment by gchoquet** [comment]
I figured it out. In my project files I changed the TargetFramework from Net5.0 to:

    <TargetFramework>net5.0-windows10.0.17763.0</TargetFramework>

I appreciate the content you post.
